Add models felix
Roberto-Ruiz-Obregon/BackEnd pull request #16
Opened 2023-03-06 22:14 UTC by felix-rojas

2023-03-06 22:21 UTC, CesarJimenezVilleda02 approved these changes

2023-03-07 01:48 UTC, DenisseDB commented
listo

2023-03-07 02:22 UTC, CesarJimenezVilleda02 requested changes

2023-03-07 02:22 UTC, CesarJimenezVilleda02 commented on models/users.model.js
> +        ref: 'User',
Este ref deberia ser a un topic no a si mismo, seria como ref: 'Topic' o el nombre que le pusiste al schema de los intereses.

2023-03-07 02:30 UTC, DenisseDB approved these changes

2023-03-07 02:50 UTC, Leonardo812 approved these changes
Lo veo bien, sin embargo tomar en consideración el comentario de Cesar, antes de realizar el merge.

2023-03-07 03:15 UTC, CesarJimenezVilleda02 approved these changes

2023-03-07 03:16 UTC, felix-rojas reviewed
El cambio sugerido de César ha sido implementado.
Quiero mencionar que agregamos la dependenica cross-env para poder correr el entorno en caso que no usen linux/mac.

2023-03-07 03:21 UTC, merged