Aggregations fer
Roberto-Ruiz-Obregon/BackEnd pull request #34
Opened 2023-03-29 21:58 UTC by FerT99

Se implementan dos controladores con aggregations para filtrar por código postal y zona con mayor inscripción de cursos.

2023-03-29 22:33 UTC, Luis-ERP requested changes

2023-03-29 22:33 UTC, Luis-ERP commented on app.js
> +app.options('*', cors());
Que esto sea una variable de entorno, porque va a cambiar en entorno de prod

2023-03-29 22:33 UTC, Luis-ERP commented on controllers/course.controller.js
> +        return next(new AppError('No se encontro un curso con ese ID.', 400));
Regrese error 404 not found, en vez de 400 bad request

2023-03-29 22:33 UTC, Luis-ERP commented on controllers/filters.controller.js
No estoy seguro que este controlador sea necesario. En el controlador de users ya se puede filtrar por topic y postalCode por medio de queryString params

2023-03-29 22:33 UTC, Luis-ERP commented on controllers/handlerFactory.controller.js
> +        let query = Model.findOne({ _id: req.params.id });
Qué ventajas tiene usar `findOne({ _id: req.params.id })` sobre findById?

2023-03-29 22:33 UTC, Luis-ERP commented on controllers/inscription.controller.js
> +/* A function that is being exported. */
Este comentario se hizo con chatgpt? no agregar valor

2023-03-29 22:33 UTC, Luis-ERP commented on example.env
> +OAUTH_CLIENTID="18102753117-atot69qilamk3me0r4a6k2mcmdluj61l.apps.googleusercontent.com"
Estas llaves deberían estar en el example.env? se ve que es info delicada

2023-03-29 22:51 UTC, CesarJimenezVilleda02 requested changes

2023-03-29 22:51 UTC, CesarJimenezVilleda02 commented on controllers/filters.controller.js
No, son aggregations, es para sacar las estadisticas, porfa pon todas las aggregaciones en un mismo archivo @FerT99 para que no se haga mas convoluted de lo que ya esta el proyecto.

2023-03-29 22:51 UTC, CesarJimenezVilleda02 commented on controllers/filters_by_zone.controller.js
> +async function getZonesWithMostInscriptions(req, res) {
Envolver funciones con el catchAsync, esta justo para ahorrarnos estos bloques try catch

2023-03-29 22:51 UTC, CesarJimenezVilleda02 commented on controllers/handlerFactory.controller.js
> +        let query = Model.findOne({ _id: req.params.id });
El findByid no permite usar population, por lo que para reemplazar las ids se tendria que hacer otra request del front.

2023-03-29 22:51 UTC, CesarJimenezVilleda02 commented on controllers/inscription.controller.js
> +/* A function that is being exported. */
Uno de los requisitos para este sprint es que arreglen todos estos comentarios.

2023-03-29 22:51 UTC, CesarJimenezVilleda02 commented on example.env
> +OAUTH_CLIENTID="18102753117-atot69qilamk3me0r4a6k2mcmdluj61l.apps.googleusercontent.com"
Habria que removerlas, estan asi mientras encontramos la forma de refreshear las tokens de forma automatica.

2023-03-29 22:51 UTC, CesarJimenezVilleda02 commented on controllers/filters.controller.js
> +          },
Aqui faltaria una fase de group para agruparlos y sumarizar, las graficas deben representar valores cuantificables.

2023-03-29 23:46 UTC, felix-rojas commented on example.env
> +OAUTH_CLIENTID="18102753117-atot69qilamk3me0r4a6k2mcmdluj61l.apps.googleusercontent.com"
> Habria que removerlas, estan asi mientras encontramos la forma de refreshear las tokens de forma automatica.

¿Igual no podíamos subir el archivo al drive? Es que si alguien encuentra la API key y con el mail_username nos podrían hacer atrocidades. Google verifica la parte de autenticación pero no hay que confiarnos.

2023-03-30 00:01 UTC, felix-rojas commented on controllers/inscription.controller.js
> +    if (course.startDate < Date.now()) {
¿Tal vez aquí agregar un margen de tiempo para inscripción? Si el curso es gratuito y comienza en la mañana y me inscribo 2 segundos antes igual me aceptaría.
Esto lo menciono por la cuestión de manejo de la lista de personas y malos actores.

2023-03-30 00:39 UTC, felix-rojas requested changes

2023-03-30 00:39 UTC, felix-rojas commented on controllers/inscription.controller.js
> +    if (course.startDate < Date.now()) {
```suggestion
    if (course.startDate < ( Date.now() - 3.6e+6 )) { // 1 hour margin
```

2023-03-30 00:39 UTC, felix-rojas commented on controllers/inscription.controller.js
> +    if (course.capacity == 0) {
```suggestion
    if (course.capacity <= 0) { // handle edge-cases where capacity might be negative
```

2023-03-30 00:39 UTC, felix-rojas commented on controllers/inscription.controller.js
> +/* A function that is being exported. */
```suggestion
/* find the courses a user is inscribed to, sorted by most recently updated courses first */
```

2023-03-30 00:39 UTC, felix-rojas commented on controllers/inscription.controller.js
> +/* A function that is being exported. */
```suggestion
/* Function to inscribe user to a course taking business rules into account*/
```

2023-03-30 00:41 UTC, CesarJimenezVilleda02 commented on example.env
> +OAUTH_CLIENTID="18102753117-atot69qilamk3me0r4a6k2mcmdluj61l.apps.googleusercontent.com"
Quieres subir el example.env a drive? La idea es que esas variables se eliminen por completo cuando pidamos las credenciales a la api de gmail

2023-03-30 00:44 UTC, CesarJimenezVilleda02 commented on controllers/inscription.controller.js
> +    if (course.startDate < Date.now()) {
Las fechas no son exactas, te podrias inscribir hasta un dia antes de que inicie el curso. Con ese codigo que agregas le dices que a las 11 de la noche el dia antes no se pueda inscribir. Igual faltaria cambiar el mensaje para clarificar por que no se puede inscribir.

Opino que se quede asi.

2023-03-30 00:46 UTC, CesarJimenezVilleda02 commented on controllers/inscription.controller.js
> +    if (course.capacity == 0) {
La capacidad nunca llega a ser negativa, el edge case no existe porque una sola inscripcion resta 1 hasta que ya no se pueden inscribir porque llega a 0, ademas hay un validador en curso que verifica que no haya capacidad negativa.

2023-03-30 03:23 UTC, DenisseDB reviewed
Considero que no sería buena idea aceptar y  mergear este par ya que tiene muchos files "nuevos" que en si ya estaban, por lo tanto, hay una probabilidad de que exista algún cambio que afecte en funcionamientos.

2023-04-02 18:43 UTC, CesarJimenezVilleda02 requested changes
Solo una aggregation sigue con lo planeado, si probandolas ves que tiene valor esta informacion podemos considerar agregar graficas de esta parte tambien.

Pero arregla o añade las que faltan.

2023-04-02 18:43 UTC, CesarJimenezVilleda02 commented on controllers/filters.controller.js
> +exports.filterTopics = async (req, res) => {
Quitar el try catch y envolver la funcion con el catchasync

2023-04-02 18:43 UTC, CesarJimenezVilleda02 commented on controllers/filters.controller.js
> +    });
Segun entiendo, con esta se filtran los usuarios que tengan ciertos topics y se encuentran en cierta zona, lo que habia que hacer con este requisito es sumarizar los intereses que mas aparecen en los usuarios de una zona, este solo deberia recibir el codigoPostal, no los topics y con el codigo postal contar los topics que tienen los usuarios de esa zona.

Tambien corrige los ejemplos de postman y agrega ejemplos como lo han estado haciendo Denisse y Alan para estas rutas, no basta con ponerle un body a la request, que por cierto, el body de esta request no tiene forma de demostrar su funcionamiento.

2023-04-02 18:43 UTC, CesarJimenezVilleda02 commented on controllers/filters.controller.js
> +  (async () => {
Este async debe ir junto a (req, res, next) en donde se crea la funcion, muevelo por favor. Tambien usar el catch async.

2023-04-02 18:43 UTC, CesarJimenezVilleda02 commented on controllers/filters.controller.js
> +exports.getZonesWithMostUsers = async (req, res) => {
Nuevamente, el catch async, ver ejemplos en handlerfactory.controller

2023-04-02 18:43 UTC, CesarJimenezVilleda02 commented on controllers/filters.controller.js
> +    ]);
Lo que tenias que hacer para este era filtrar usuarios por codigo postal y de esos usuarios buscar sus inscripciones contanto a que cursos se habian inscrito mas. Se debe producir un resultado como "Nombre de curso": numero de inscripciones. Recordemos nuevamente que esta grafica y la anterior deben solo recibir el codigo postal y obtener estos datos.

2023-04-19 04:26 UTC, Luis-ERP commented on app.js
> +    max: 1000,
Unas buenas prácticas es poner estas constantes en un archivo separado o como variables de entorno

2023-04-19 04:31 UTC, Luis-ERP commented on models/programs.model.js
> +        hasLimit: {
En mi opinión este campo es innecesario, con checar si limitDate es nulo ya sabes qué onda

2023-04-19 04:33 UTC, Luis-ERP approved these changes

2023-04-30 03:54 UTC, merged