Spelling denisse
Roberto-Ruiz-Obregon/BackEnd pull request #36
Opened 2023-03-30 03:50 UTC by DenisseDB

Corrección de ortografía

2023-03-30 22:51 UTC, FerT99 commented on views/emails/paymentAcceptedAlert.pug
> +  p Hemos aceptado tu pago para el curso #{course.courseName}, pronto recibiras un correo de confirmacion de inscripcion.
hay que agregar los acentos: recibirás*, inscripción*, confirmación*

2023-03-30 22:55 UTC, FerT99 commented on views/emails/paymentRejectedAlert.pug
> +  p ¡Si crees que hay un problema no dudes en contactarnos o iniciar el proceso de pago de nuevo!
Sugiero nadamás cambiar el signo de admiración: 

Si crees que hay un problema, ¡no dudes en contactarnos o iniciar el proceso de pago de nuevo!

2023-03-30 22:58 UTC, FerT99 requested changes
son poquitos cambios los que hay que hacer, fuera de eso todo bien

2023-04-01 00:30 UTC, FerT99 approved these changes

2023-04-02 01:47 UTC, CesarJimenezVilleda02 approved these changes

2023-04-02 01:47 UTC, merged