Image bug e indexing
Roberto-Ruiz-Obregon/BackEnd pull request #40
Opened 2023-04-18 22:03 UTC by alanrazop

+ Se realizó un indexing para los cursos por medio del id del curso y su nombre
+ Se agregaron mensajes de error para cuando se sube un archivo con mas de 10 MB

2023-04-19 04:38 UTC, Luis-ERP requested changes

2023-04-19 04:38 UTC, Luis-ERP commented on controllers/errorController.controller.js
> +            res.status(500).json({
Que devuelva error 400 (bad request) en vez de 500 (server error), ya que esto es error del usuario, no del servidor

2023-04-19 04:38 UTC, Luis-ERP commented on controllers/errorController.controller.js
> +            res.status(500).json({
Lo mismo aquí

2023-04-19 04:38 UTC, Luis-ERP commented on models/courses.model.js
> +        courseId: {
Mongoose crea por defecto un campo _id, para qué se agrega este courseId?

2023-04-19 04:38 UTC, Luis-ERP commented on models/courses.model.js
> +        courseId: {
Mongo*

2023-04-19 06:19 UTC, CesarJimenezVilleda02 commented on models/courses.model.js
> +        courseId: {
Si, el que estamos usando es el de la pripiedad _id en todos los documentos. Borrar esto.

2023-04-19 06:26 UTC, CesarJimenezVilleda02 commented on models/courses.model.js
> +courseSchema.index({ courseId: 1, courseName: "text" });
```suggestion
courseSchema.index({ _id: 1});
```

EJEMPLO:
tourSchema.index({ price: 1 });
tourSchema.index({ ratingsAverage: -1 });
tourSchema.index({ slug: 1 });
// ESTOS SON COMBINADOS, 1 es ascendente y -1 descendente. 
tourSchema.index({ price: 1, ratingsAverage: -1 });

Por favor, crea uno para _id, para status, modality, courseName y postalCode. Todos por separado.

2023-04-19 06:31 UTC, CesarJimenezVilleda02 commented
Tambien necesitamos:
- En program por programName, _id y category
- En users por email y _id
- En payments por status, course y user
- En inscriptions por user y course
- En admins por email

2023-04-19 06:32 UTC, CesarJimenezVilleda02 requested changes
No es necesaria la propiedad index en el campo que se desea indexar, ve el ejemplo en mis comentarios y siguelo.

2023-04-24 05:45 UTC, CesarJimenezVilleda02 commented
Agrega un test para ver si el error de la imagen si se envia

2023-04-25 07:13 UTC, merged